---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: winesapos-repo
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            autoindex on;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-winesapos-repo
  namespace: winesapos-repo
  labels:
    app: winesapos-repo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winesapos-repo
  template:
    metadata:
      labels:
        app: winesapos-repo
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 256Mi
          volumeMounts:
            - name: pvc-winesapos-repo
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: pvc-winesapos-repo
          hostPath:
            path: /data/winesapos-repo
            type: Directory
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
