---
kind: Service
apiVersion: v1
metadata:
  name: svc-winesapos-repo
  namespace: winesapos-repo
  labels:
    app: winesapos-repo
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: winesapos-repo
  type: ClusterIP
