name: winesapOS image build with Manjaro
on:
  push:
    branches-ignore:
      - stable
    paths-ignore:
      - '*.md'
      - 'scripts/repo/**'
      - scripts/winesapos-upgrade.sh
jobs:
  build:
    name: System image build
    runs-on: ubuntu-24.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
            root-reserve-mb: 10240
            swap-size-mb: 2048
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Install Bash
        run: sudo apt-get update && sudo apt-get install -y bash shellcheck
      - name: Check syntax of scripts
        run: |
          for i in $(find . -name "*.sh" | sort)
              do echo "${i}"
              if ! bash -n "${i}"; then
                  exit 1
              fi
              if ! shellcheck "${i}"; then
                  exit 1
              fi
          done
      - name: Obtain base docker image
        run: docker pull manjarolinux/base:latest
      - name: Configure Manjaro for the container build
        run: sed -i s'/archlinux:latest/manjarolinux\/base:latest/'g build/Dockerfile
      - name: Create docker build image
        run: docker build --pull --no-cache -t winesapos-img-builder build/.
      - name: Build system image
        id: build_image
        run: docker run --rm -v $(pwd):/workdir -v /dev:/dev --env WINESAPOS_DISTRO=manjaro --env WINESAPOS_DEBUG_INSTALL=true --env WINESAPOS_DEBUG_TESTS=true --env WINESAPOS_ENABLE_PORTABLE_STORAGE=false --env WINESAPOS_CREATE_DEVICE_SIZE=9 --privileged=true winesapos-img-builder:latest /bin/bash -x /workdir/scripts/winesapos-build.sh
