name: winesapOS rolling Pacman repository build
on:
  push:
    branches:
      - main
    paths:
      - 'scripts/repo/**'
  schedule:
    # Run at midnight on the 15th day of each month.
    # Scheduled GitHub Actions workflows may be delayed by up to an hour.
    - cron: '0 0 15 * *'
  workflow_dispatch:
jobs:
  build:
    name: System image build
    runs-on: ubuntu-24.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
            root-reserve-mb: 16384
            swap-size-mb: 2048
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Obtain base docker image
        run: docker pull archlinux:latest
      - name: Create container build image
        run: docker build --pull --no-cache --tag ekultails/winesapos-build-repo:latest scripts/repo/
      - name: Create output directory
        run: mkdir output && chmod 777 output
      - name: Build winesapOS testing repository
        id: build_repo_testing
        run: |
          docker run \
            --name winesapos-build-repo \
            --rm \
            --env WINESAPOS_REPO_BUILD_ROLLING=true \
            --env WINESAPOS_REPO_SIGN=true \
            --env WINESAPOS_REPO_GPG_PRIVATE_KEY="${{ secrets.PACMAN_GPG_PRIVATE_KEY }}" \
            --env WINESAPOS_REPO_GPG_PASSWORD="${{ secrets.PACMAN_GPG_PASSPHRASE }}" \
            --volume "$(pwd)/output":/output \
            ekultails/winesapos-build-repo:latest
      - name: Check status code
        # Provide the return code without actually exiting.
        run: (exit $(cat ./output/winesapos-build-repo_exit-code.txt))
      # The REPO_SSH_KEY secret in GitHub needs to have a newline character added to the end.
      # Otherwise, we get the following error:
      # Load key "/home/runner/.ssh/repo.key": invalid format
      # https://serverfault.com/questions/854208/ssh-suddenly-returning-invalid-format
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo -e "${SSH_KEY}\n" > ~/.ssh/repo.key
          chmod 600 ~/.ssh/repo.key
          cat >>~/.ssh/config <<END
          Host repo
            HostName ${SSH_HOST}
            User ${SSH_USER}
            IdentityFile ~/.ssh/repo.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.REPO_SSH_USER }}
          SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
          SSH_HOST: ${{ secrets.REPO_SSH_HOST }}
      - name: Back up old repository files
        run: ssh repo "mv /data/winesapos-repo/repo/winesapos-rolling /data/winesapos-repo/repo/winesapos-rolling_$(date --iso-8601=seconds)"
      - name: Create new repository folder
        run: ssh repo "mkdir -p /data/winesapos-repo/repo/winesapos-rolling/x86_64"
      - name: Copy the new repository over to the server
        run: rsync -avurP ./output/ repo:/data/winesapos-repo/repo/winesapos-rolling/x86_64/
